project_id = "ikjcjfhgnmiixjsqadrm"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-episode-access]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.approve-producer]
verify_jwt = false

[functions.create-video-upload]
verify_jwt = false

[functions.create-purchase-intent]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.calculate-referral-commission]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
